spring:
  datasource:
    initialization-mode: always
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgres://dkoggkzyaccrmw:6efd72bc93767b5fae935a4b56120dcbc6a9e2b3abb2bc936f753d29dcf89ac8@ec2-54-146-116-84.compute-1.amazonaws.com:5432/d9q5ivhuga35is
    username: dkoggkzyaccrmw
    password: 6efd72bc93767b5fae935a4b56120dcbc6a9e2b3abb2bc936f753d29dcf89ac8

server:
  port: 8080

app:
  execute:
    user: 佐々木渉
  google:
    oauth2-url: https://www.googleapis.com/oauth2/v4/token
    api-url: https://sheets.googleapis.com/v4/spreadsheets/
    sheet-id: 13RqLVAYKnbff6f5cWPzqyh-1y5j8NC_brqI_Le73qhI
    client-id: 455165694555-gekiq4j8upinbq5kejusq7t92r7t560v.apps.googleusercontent.com
    client-secret: 6r7S3FqjssNuXM8FbKa-GLX0
    refresh-token: 1//0eUMWJyOCHBimCgYIARAAGA4SNwF-L9IrbwgtJYYyS1qfAi-0l2d_LjZaK1Cth6FbicCFBEeoJjc8rVdHHM5sye1xQDDuv7KHDic
